### ISSUE TITLE
Does it supports comparison of multiple screenshot within same test

### ISSUE THREAD

**Issue by aprabh001c** [tacoss/testcafe-blink-diff#10]
if i add multiple takeSnapshot step it is replacing existing screenshot and retaining only last taken screenshot

e.g.m
test('check something here', async t => {
1 await t    .click('select1') 
  // then pass the `t` reference to invoke the helper
2 await takeSnapshot(t);
3 await t    .click('select2')    .expect('...')    .ok();
4 await takeSnapshot(t);
});

Here i am taking two screenshots in step 2 & 4. But i see only one screenshot in provided location.

Is there any way i can take multiple screenshots and compare them

**Comment by pateketrueke** [comment]
Interesting use-case, let me see if there's a chance of solving that with the current implementation.

Otherwise I'll nee to design and implement such feature, thanks for your input!

**Comment by aprabh001c** [comment]
Thanks for your response, please update your decision.

**Comment by aprabh001c** [comment]
could you please update on this

**Comment by pateketrueke** [comment]
Yeah, sorry, I have not time yet to investigate, hopefully this weekend I got some spare time for!

**Comment by pateketrueke** [comment]
Snapshots can be named, so you can do `takeSnapshot(t, 'foo')` but even if you have named snapshots they'll saved into the same base folder.

> The diffing thechnique compares two images from different base folders, so this approach does not work by design.

Ideally you would want to see visual diffing between runs, not between steps, however you can setup a different  base to save the snapshot, e.g.

```js
// step 2
takeSnapshot(t, { base: 'foo' })

// step 4
takeSnapshot(t, { base: 'bar' });
```

This `base` option will serve to save the taken snapshot into a different folder, then you can later run `npx testcafe-blink-diff  --compare foo:bar` as usual.
