### ISSUE TITLE
Error: takeSnapshot() failed with the latest version with latest 0.4.5

### ISSUE THREAD

**Issue by wendywww** [tacoss/testcafe-blink-diff#14]
I know people reported same issue before on older version and it's supposed to resolved. 

With the instructed steps with npm install(`npm i testcafe-blink-diff --save-dev`), there's some complaining found 7 vulnerabilities (6 low, 1 high).  Disregard it, I am able to run test successfully and generate the visual comparison. 
<img width="1278" alt="Screen Shot 2020-04-13 at 1 39 32 AM" src="https://user-images.githubusercontent.com/5750536/79106777-fd97c500-7d27-11ea-95c9-307b5eb3a029.png">

However when I install with my current framework ( by yarn add --dev testcafe-blink-diff@0.4.5) I am not able to run test successfully. All our package is installed with yarn, so we tend to do the 2nd way. Could u please look into why it's failing while I install with yarn? 
Also seems like in this case when I run, the local server connection is killed.

<img width="1097" alt="Screen Shot 2020-04-13 at 1 32 21 AM" src="https://user-images.githubusercontent.com/5750536/79106142-c674e400-7d26-11ea-9c2e-4d2f912ad4d8.png">

**Comment by pateketrueke** [comment]
An screenshot is not very helpful... actually there should not be differences between yarn or npm, can you share your package.json and yarn.lock to try locally?

**Comment by pateketrueke** [comment]
Hi, please try the latest release, thank you!

If the issue remains, please reopen this ticket.
