### ISSUE TITLE
fullPage snapshot

### ISSUE THREAD

**Issue by Ramnath85** [tacoss/testcafe-blink-diff#15]
Hello,

Could you share a sample command to enable fullPage snapshots please?
If I provide "fullPage: true" inside await takeSnapshot(t), it is getting errored out.

Thanks.

**Comment by pateketrueke** [comment]
> If I provide "fullPage: true" inside await takeSnapshot(t), it is getting errored out.

Can you share wich version you're using and the error you're getting? Thank you!

**Comment by Ramnath85** [comment]
I guess the syntax am using is not correct.  I tried different one.  For example, await takeSnapshot(t, [options.fullPage]).  Could you please let me know the correct syntax to be used in this case?
version: 0.4.5
IDE: visual code

**Comment by pateketrueke** [comment]
Please check out [this comment](https://github.com/tacoss/testcafe-blink-diff/issues/9#issuecomment-555086987).

**Comment by Ramnath85** [comment]
thank you.  I tried it now.  Testcafe's inbuilt takeScreenshot method is able to take full page screenshot when I give this:
```
await t.takeScreenshot({
        fullPage: true
    });
```
But the takeSnapshot still capture only the visible portion of the page with the below code.  
```
await t.takeScreenshot({
        fullPage: true
    });
    await takeSnapshot(t)
```

**Comment by pateketrueke** [comment]
Interesting, I think I'll add some tests to make sure we're following the Testcafé API, thank you!

**Comment by pateketrueke** [comment]
Gotcha, actually I noticed what's wrong with this code:

```js
await t.takeScreenshot({
  fullPage: true
});
await takeSnapshot(t)
```

Two screenshots are taken, but the later one overrides the first one because they're using the same label (default to the testcase name, not random) — to fix this, use `takeSnapshot(t, { label: 'a', fullPage: true })`

**Comment by vgangwar8** [comment]
Hi Pateketrueke,
last 2 pages of the full screenshot are getting skipped our blacked out.
Is there any way where we can take a clear full screenshot.
Please have a look the below screenshot.
![actual@1 5](https://github.com/user-attachments/assets/7c59c589-91f0-4577-a82e-5f99e2641bd2)
@pateketrueke
