### ISSUE TITLE
Different functions for taking base and actual screenshots

### ISSUE THREAD

**Issue by emannuelOC** [tacoss/testcafe-blink-diff#2]
It would be nice to have different functions for taking base snapshots (something like `recordSnapshot(t)`) and taking actual snapshots. Then we would be able to record a new base snapshot for only one part of the code without saving new snapshots for the rest.

A similar approach was used in [this iOS snapshot testing library](https://github.com/ashfurrow/Nimble-Snapshots).

What do you think?

**Comment by pateketrueke** [comment]
Sound good, could you add an example of how it would be? (not the impl. just the usage)

**Comment by emannuelOC** [comment]
Say you're working on `Feature B` and the layout has changed, so you wanna record a new snapshot model for that feature. However, you may have added some bugs to feature A in the process so you don't wanna record the snapshots for A, only for B.

The code would look somewhat like the example below. After the first run, you would replace  `recordSnapshot(t)` in the second test with `takeSnapshot(t)`.

```
import { takeSnapshot } from 'testcafe-blink-diff';

fixture('Snapshots')
  .page('http://localhost:8080');

test('check feature A', async t => {
  await t
    .click('...')
    .expect('...')
    .ok();

  // take the snapshot normally in order to compare with the model
  await takeSnapshot(t);
});

test('check feature B', async t => {
  await t
    .click('...')
    .expect('...')
    .ok();

  // record a new model for feature B only
  await recordSnapshot(t);
});

```

**Comment by pateketrueke** [comment]
Gotcha!

I'll be working on that asap, so much thanks for your feedback!

**Comment by pateketrueke** [comment]
Hi, sorry for being late but this won't be implemented as `takeSnapshot` is not used for asserting, it will just take snapshots, exactly as `recordSnapshot` would be.

Calling the binary is the only way to validate differences between snapshots, e.g. `npx testcafe-blink-diff folder/ --compare a:b`
