### ISSUE TITLE
[Bug] Missing screenshot error exits with success error code

### ISSUE THREAD

**Issue by VitalyEmelyanov** [tacoss/testcafe-blink-diff#26]
When there are missing screenshots, the error is printed, but the exit code is 0.
This is confusing, especially when using in the CI.

**Actual:**
The command exits with code 0

**Expected:**
The command should exit with an error code

<img width="710" alt="scr" src="https://user-images.githubusercontent.com/15330670/108475022-d63f4c00-7298-11eb-9e0f-f33249124b4e.png">

**Comment by pateketrueke** [comment]
Which version are you using? We already fixed it on https://github.com/tacoss/testcafe-blink-diff/commit/d5c50b64ba8e9277aa0738b67daed47afb37b934 and it's already released on v0.4.8

**Comment by VitalyEmelyanov** [comment]
> Which version are you using? We already fixed it on [d5c50b6](https://github.com/tacoss/testcafe-blink-diff/commit/d5c50b64ba8e9277aa0738b67daed47afb37b934) and it's already released on v0.4.8

I was on previous 0.4.7, thanks for clarifying
