### ISSUE TITLE
Question about taking a selector snapshot

### ISSUE THREAD

**Issue by oleg-bc** [tacoss/testcafe-blink-diff#31]

**Comment by pateketrueke** [comment]
A `selector` is a string or `Selector` instance, e.g.

```js
import { Selector } from 'testcafe';

const toast = '#toast-id'; // or `const toast = Selector('#toast-id');`

// ... later in your tests:
await takeSnapshot(toast);
```

The syntax you used for `t.selector[toast]` is not valid, as there are is `t.selector` API available, which I am think is your issue.
