### ISSUE TITLE
unknown option --take-snapshot error is coming

### ISSUE THREAD

**Issue by njain2-rms** [tacoss/testcafe-blink-diff#4]
I am running the tests with below command :
node node_modules/testcafe/bin/testcafe --take-snapshot

and I am getting an error :  unknown option --take-snapshot .

Also, Do I need to pass in function await takeSnapshot(t) in each test wherever I want to capture screenshot and then compare ?

**Comment by pateketrueke** [comment]
Seems like testcafé is now validating all argv, try prepending `--` before those flags, e.g. `testcafe -- --take-snapshot`

If this not works I'll send a patch for it asap, thank you!

**Comment by njain2-rms** [comment]
This is also not working

node node_modules/testcafe/bin/testcafe -- --take-snapshot

It thinks that arg (take snapshot) is tests to be run. It throws below error:

The "src" option from the configuration file will be ignored.
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

Please look into this issue

**Comment by pateketrueke** [comment]
> Please look into this issue

You're still missing arguments for testcafé; first make it run, once run, add the ` -- --take-snapshot` flag at the end.

```
node node_modules/testcafe/bin/testcafe [ARGS MISSING HERE] -- --take-snapshot
```

Please read testcafe's documentation before.

**Comment by njain2-rms** [comment]
Hi,

I am not passing any arguments for test cafe as I am using Test Cafe config file - .testcaferc.json.
Can't I make this work without passing in  test cafe arguments ?

**Comment by pateketrueke** [comment]
Help me to understand:

- when you run testcafé, as usual, without using this plugin it works as expected, right?

If that's true, then it's our fault, so I need time to investigate your issue and add corrections to make it work.

> Also, Do I need to pass in function await takeSnapshot(t) in each test wherever I want to capture screenshot and then compare ?

Yes, by now.

I mean, this plugin won't take snapshots from everything, you need to be explicit in order to take full control over.

**Comment by njain2-rms** [comment]
Yes, I run testCafe with command node node_modules/testcafe/bin/testcafe as all the things like src, screenshotPath are defined in .testcaferc.json. as below 

`"screenshotPath": "./reports/screenshots/",
    "screenshotPathPattern": "${DATE}_${TIME}/fixture-${FIXTURE}/${USERAGENT}/test-${TEST}.png",
    "src": "./tests/*.js",`

**Comment by pateketrueke** [comment]
Gotcha, I'll review this asap, thank you!

**Comment by pateketrueke** [comment]
I've added a `TAKE_SNAPSHOT=true` support instead of passing `--take-snapshot`, so you can do it this way: `TAKE_SNAPSHOT=true npx testcafe`
