### ISSUE TITLE
no chance to build report in win10

### ISSUE THREAD

**Issue by maximkoev** [tacoss/testcafe-blink-diff#5]
Hi Alvaro, excuse me for disturbing.
When i try to build report got an error message "The system cannot find the path specified."

I executed command 
`npx testcafe ./testcafe/src/tests/layout -s ./testcafe/scripts/data/test --take-snapshot base` to make base and actual snapshots it works ok, but when I run 
`npx testcafe-blink-diff testcafe/scripts/data/test  --compare base:actual --open --threshold 0.03`
got an error

**Comment by pateketrueke** [comment]
You're missing the `-s` argument on your second call.

I mean, is not a problem with this module, is bad usage of the main Testcafé binary, please check their documentation.

**Comment by maximkoev** [comment]
@pateketrueke I can't find logs, just tell me where is -s argument lost?

**Comment by pateketrueke** [comment]
No, sorry, I confused both commands as the same, my fault.

The logs I'm looking for are those are you seeing at your screen when you run that command, can you copy and paste that completely?

**Comment by maximkoev** [comment]
please find log in pic attached

![image](https://user-images.githubusercontent.com/15101695/58886504-af1fa000-86ec-11e9-9b1a-9dfb5f4181ad.png)

**Comment by pateketrueke** [comment]
Now I understand, actually it's an issue from the binary itself because we're not shipping a compatible one for Windows.

I'm not Windows user, but I can try to solve that on a VM or something like that... however if you were able to do that I'll be happy to accept your PR for it! 🍻

**Comment by maximkoev** [comment]
I am not sure that my skill is enough to fix it :)

**Comment by pateketrueke** [comment]
Don't worry, I will work on this asap, probably is not sooo complicated.
