### ISSUE TITLE
Actual files saved have @2 appended to file name.

### ISSUE THREAD

**Issue by vlads11** [tacoss/testcafe-blink-diff#57]
Hi BlinkDiff team,

Reaching out for some help and guidance on 2 issues we're experiencing when trying to integrate blinkdiff into our automation repo.

1)  Zwift Hub Snapshots
 ✓ Home page (screenshots: /Tests-Visual/screenshots/vlad/Zwift_Hub_Snapshots/Full_Home_Page/actual@2.png)
 -- When actual and base images are saved they @2 is appended to the image name and I am not sure why.
 2) Issues running blinkdiff test via Jenkins in a docker container, same call in jenkins results in base.png being saved (no @2 appended).
 
 Pretty sure the 2 issues are related but not sure what could be causing the inconsistency with the file-saving system. Any help is much appreciated.

**Comment by pateketrueke** [comment]
Hi, the `@2` is the DPI from the browser that took the screenshots, if no `@2` is present that means the DPI on that browser (may be headless?) is just 1, so we're not adding the suffix since it's the default.

Why and for what purpose? That value helps us to determine the DPI from images to be compared, because different DPI yields different image resolutions, so we need to know the DPI from both images to scale them properly and then run the diff.

**Comment by vlads11** [comment]
TY @pateketrueke for the explanation on the @2. Learned something new =)

I can see everything working locally now which is awesome but running the our test suite in a docker container via Jenkins still only captures the base.png.

`node ./zwift-blinkdiff.js -e production --browser firefox:headless -s ./Tests-Visual/screenshots/vlad --testMeta.robinTest --take-snapshot actual
Executing TestCafe runner.
Credentials - Environment data found.
 Running tests in:
 - Firefox 106.0 / Alpine Linux 3.17_alpha20220715

 Zwift Hub Snapshots
 ✓ Home page (screenshots: /home/jenkins/agent/workspace/TestCafe/Blinkdiff-Visual-Regression-Actual/Zwift-TestCafe/Tests-Visual/screenshots/vlad/Zwift_Hub_Snapshots/Full_Home_Page/base.png)`
 
 Any thoughts or ideas on why running in the cloud/docker would be a problem?

**Comment by pateketrueke** [comment]
I am curious about your `./zwift-blinkdiff.js` script, what it does exactly?

**Comment by vlads11** [comment]
Added the files below - We use them to pass and set various parameters for the job execution (environment variables, window screen sizes, metadata, etc)


zwift-blinkdiff.js
`let yargs;                 // Unsure why I have to do this for yargs.
yargs = require('yargs');  // If I dont, code inspection fails.
const dateFormat = require('dateformat');
const testCafe = require('testcafe');

let testCafeInst = null;

const environmentConfig = require('./Config/EnvironmentConfig');
const viewports = require('./Config/Viewport.json');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { locale } = require('yargs');
const defaultSrcPath='./Tests-Visual';

//////////////////////////////////////////////////////////////
// Main                                                     //
//////////////////////////////////////////////////////////////

let uniqueInstanceIdentifier;
let artifactPath;
const nowDateTimeString = dateFormat(new Date(), 'yyyy-mm-dd_HH-MM-ss');

// Process all arguments.
ProcessArguments();

const fullArtifactPath = path.join(artifactPath, uniqueInstanceIdentifier, os.platform());

// Validate environment data is present.
ValidateEnvironment(yargs.argv.environment);

// Update configuration JSON.
UpdateTestCafeConfiguration();

// Run Test Cafe!
if (!yargs.argv.skipTestCafeLauncher) {
	testCafe()
		.then(tc => {
			console.log('Executing TestCafe runner.');
			testCafeInst = tc;
			const runner = testCafeInst.createRunner();
			return runner.run();
		})
		.then(() => {
			process.exit(0);
		});
}

//////////////////////////////////////////////////////////////
// Helper Methods                                           //
//////////////////////////////////////////////////////////////

function UpdateTestCafeConfiguration() {
	const cafeJson = LoadTestCafeConfig();

	const environmentName = yargs.argv.environment.toLowerCase();
	// Update environment.
	cafeJson.environment = environmentName;

	// Update environmentProject
	cafeJson.locale = yargs.argv.locale;

	cafeJson.disableAllureReporting = yargs.argv.disableAllureReporting;
	if (!yargs.argv.disableAllureReporting) {
		console.log('Allure Reporting Enabled');
		cafeJson.reporter.push('allure');
	}

	cafeJson.filter.testMeta = yargs.argv.testMeta;
	cafeJson.filter.fixtureMeta = yargs.argv.fixtureMeta;
	cafeJson.filter.fixtureGrep = yargs.argv.fixtureGrep;

	// Set DisplayType
	if (yargs.argv.windowDisplayType != 'custom') {
		//Validate DisplayType value
		var displayTypes = [
			'custom',
			'desktop',
			'tablet',
			'mobile',
			'all'
		];
		if (!displayTypes.includes(yargs.argv.windowDisplayType)) {
			throw Error('The --windowDisplayType value was not valid. Examples: custom, desktop, tablet, mobile');
		}

		switch (yargs.argv.windowDisplayType) {
			case 'desktop': {
				yargs.argv.windowResolution[0] = viewports['desktop']['width'];
				yargs.argv.windowResolution[1] = viewports['desktop']['height'];
				cafeJson.filter.testMeta.bExecDisplayTypeDesktop = true;
				cafeJson.filter.fixtureMeta.bExecDisplayTypeDesktop = true;
				break;
			}
			case 'tablet': {
				yargs.argv.windowResolution[0] = viewports['tablet']['width'];
				yargs.argv.windowResolution[1] = viewports['tablet']['height'];
				cafeJson.filter.testMeta.bExecDisplayTypeTablet = true;
				cafeJson.filter.fixtureMeta.bExecDisplayTypeTablet = true;
				break;
			}
			case 'mobile': {
				yargs.argv.windowResolution[0] = viewports['tablet']['width'];
				yargs.argv.windowResolution[1] = viewports['tablet']['height'];
				cafeJson.filter.testMeta.bExecDisplayTypeMobile = true;
				cafeJson.filter.fixtureMeta.bExecDisplayTypeMobile = true;
				break;
			}
			case 'custom':
			default: {
				break;
			}
		}
	}

	// Set browserHeight and browserWidth
	if (yargs.argv.windowResolution.length != 2) {
		throw Error('The --windowResolution option must include a HEIGHT WIDTH value. Example: --windowResolution 1920 1080');
	}
	cafeJson.windowResolution = yargs.argv.windowResolution;

	// Update source test path if an override is provided.
	if (yargs.argv.sourcePathOverride && yargs.argv.sourcePathOverride.trim().length > 0) {
		cafeJson.src = yargs.argv.sourcePathOverride;
	} else {
		// Set the default source path if none is passed. This will ensure that the value is reset if a previous ru
		// uses a different directory.
		cafeJson.src = defaultSrcPath;
	}

	cafeJson.concurrency = yargs.argv.concurrentClients;
	cafeJson.screenshots.takeOnFails = !yargs.argv.disableScreenshotsOnFails;
	cafeJson.quarantineMode = !yargs.argv.disableQuarantineMode;
	cafeJson.skipJsErrors = !yargs.argv.disableSkipJsErrors;

	// Setup production vs dev-environment meta data.
	// eslint-disable-next-line no-constant-condition
	if (cafeJson.environment === 'production') {
		cafeJson.filter.testMeta.bExecProduction = true;
		cafeJson.filter.fixtureMeta.bExecProduction = true;
	} else if (cafeJson.environment === 'staging') {
		cafeJson.filter.testMeta.bExecStaging = true;
		cafeJson.filter.fixtureMeta.bExecStaging = true;
	} else {
		cafeJson.filter.testMeta.bExecDevEnvs = true;
		cafeJson.filter.fixtureMeta.bExecDevEnvs = true;
	}

	// Setup locale metadata filters
	if (cafeJson.locale === 'us') {
		cafeJson.filter.testMeta.bExecUSlocale = true;
		cafeJson.filter.fixtureMeta.bExecUSlocale = true;
	} else if (cafeJson.locale === 'eu') {
		cafeJson.filter.testMeta.bExecEUlocale = true;
		cafeJson.filter.fixtureMeta.bExecEUlocale = true;
	} else if (cafeJson.locale === 'uk') {
		cafeJson.filter.testMeta.bExecUKlocale = true;
		cafeJson.filter.fixtureMeta.bExecUKlocale = true;
	}

	// Set browsers.
	cafeJson.browsers = yargs.argv.browser;

	// Update enabledFeatures feature flags
	if (yargs.argv.enabledFeatures) {
		console.log(`WARN: Feature flags enabled:\n\t${ yargs.argv.enabledFeatures.split(',').join('\n\t') }`);
		cafeJson.enabledFeatures = yargs.argv.enabledFeatures;
	}

	cafeJson.compare = yargs.argv.compare;

	cafeJson.takeSnapshot = yargs.argv['take-snapshot'];
	if (cafeJson.takeSnapshot === 'base') {
		fs.rm('./generated', { recursive: true }, () => {
			console.log('generated folder deleted');
		});
		fs.rm('./Tests-Visual/screenshots', { recursive: true }, () => {
			console.log('Test-Visual/screenshots folder deleted');
		});
	}

	// CHANGED THIS
	// Update screenshot path.
	cafeJson.screenshots.path = yargs.argv.saveScreenshot;

	SaveTestCafeConfig(cafeJson);

}

function LoadTestCafeConfig() {
	if (fs.existsSync('./Config/testcaferc-template.json')) {
		const configBuffer = fs.readFileSync('./Config/testcaferc-template.json');
		const configJsonString = configBuffer.toString();
		return JSON.parse(configJsonString);
	} else {
		return {};
	}
}

function SaveTestCafeConfig(testCafeConfig) {
	const testConfigString = JSON.stringify(testCafeConfig);
	fs.writeFileSync('./.testcaferc.json', testConfigString);
	fs.mkdirSync(fullArtifactPath, { recursive: true });
	fs.writeFileSync(path.join(fullArtifactPath,'testcaferc.backup.json'), testConfigString);
}

function ValidateEnvironment(environmentName) {
	if (environmentConfig[environmentName] === undefined) {
		console.log('ERROR: Environment data for `' + environmentName + '` does not exist!');
		process.exit(1);
	}
}

/**
* helper function that sets metadata for specified viewport
*/
async function setMetaForViewport(displayType) {
	const cafeJson = LoadTestCafeConfig();

	switch (displayType) {
		case 'desktop': {
			cafeJson.filter.testMeta.bExecDisplayTypeDesktop = true;
			cafeJson.filter.fixtureMeta.bExecDisplayTypeDesktop = true;
			break;
		}
		case 'tablet': {
			cafeJson.filter.testMeta.bExecDisplayTypeTablet = true;
			cafeJson.filter.fixtureMeta.bExecDisplayTypeTablet = true;
			break;
		}
		case 'mobile': {
			cafeJson.filter.testMeta.bExecDisplayTypeMobile = true;
			cafeJson.filter.fixtureMeta.bExecDisplayTypeMobile = true;
			break;
		}
		default: {
			break;
		}
	}
}
// eslint-disable-next-line no-undef
module.exports = setMetaForViewport;

function ProcessArguments() {
	yargs
		.command('*', 'Launch Zwift Blinkdiff Suite')
		.alias('help', 'h')
		.alias('version', 'v')
		.options({
			environment: {
				alias: 'e',
				describe: 'Target environment name. See ./Config/EnvironmentConfig.json',
				type: 'string',
				demandOption: false
			},
			environmentProject: {
				describe: 'Target environment project name, ex) "shpx", "etas", or "disco"',
				type: 'string',
				default: ''
			},
			uniqueIdentifier: {
				describe: 'Unique identifier for this execution. Used when creating report and artifact ' +
					'paths. If not provided, datetime format will be used. (%Y-%m-%d_%H-%M-%S)',
				type: 'string'
			},
			disableQuarantineMode: {
				describe: 'Disable quarantine mode.',
				type: 'boolean',
				default: false
			},
			disableSkipJsErrors: {
				describe: 'Disable the skipping of JS errors during tests.',
				type: 'boolean',
				default: false
			},
			concurrentClients: {
				describe: 'The number concurrent clients of each browser will launch.',
				type: 'number',
				default: 1
			},
			disableScreenshotsOnFails: {
				describe: 'Disable screenshots on failures.',
				type: 'boolean',
				default: false
			},
			sourcePathOverride: {
				describe: 'Test search path override. Relative to script location or full path.',
				type: 'string'
			},
			fixtureMeta: {
				describe: '{metaPropertyName}="test value" - Can stack multiple properties with additional entries of `--fixtureMeta.propertyName=value --fixtureMeta.propertyName=value`.\nExample:\n' +
					'String: --fixtureMeta.propertyName="test string"\n' +
					'Number: --fixtureMeta.propertyName=123\n' +
					'Bool (true): --fixtureMeta.propertyName\n' +
					'Bool (false): --no-fixtureMeta.propertyName',
				type: 'object',
				default: {}
			},
			fixtureGrep: {
				describe: 'Run fixtures that match the regex. `--fixture-grep=\'Clubs.*\'`',
				type: 'string',
			},
			testMeta: {
				describe: '{metaPropertyName}="test value" - Can stack multiple properties with additional entries of `--testMeta.propertyName=value --testMeta.propertyName=value`.\nExample:\n' +
					'String: --testMeta.propertyName="test string"\n' +
					'Number: --testMeta.propertyName=123\n' +
					'Bool (true): --testMeta.propertyName\n' +
					'Bool (false): --no-testMeta.propertyName',
				type: 'object',
				default: {}
			},
			browser: {
				describe: 'Add specific browsers by using --browser multiple times. If no browser is presented, CHROME will be set as the default.\n'
					+ 'Example:\n'
					+ '--browser=chrome --browser=firefox\n'
					+ 'Will execute the suite on both chrome and firefox browsers.',
				type: 'array',
				default: []
			},
			windowResolution: {
				describe: 'Set view size to to specific width and height. If both width/height are 0, the browser will maximize. Example: `--windowResolution 1920 1080`',
				type: 'array',
				default: [0,0],
			},
			windowDisplayType: {
				describe: 'Overrides the windowResolution with default resolution based on type. Valid types: custom, desktop, tablet, mobile. Example: `--windowDisplayType mobile`',
				type: 'string',
				default: 'custom'
			},
			enabledFeatures: {
				alias: 'featureFlags',
				describe: 'Used to activate feature flags via the url query parameter "?enabledFeatures=comma,separated,flags"',
				type: 'string'
			},
			disableAllureReporting: {
				describe: 'Disable Allure reporting',
				type: 'boolean',
				default: false
			},
			locale: {
				alias : 'l',
				describe: 'Shopify Url locale, ex: "uk", "us", or "eu"',
				type: 'string',
				default: 'us'
			},
			saveScreenshot: {
				alias: 's',
				describe: 'Directory to store blinkdiff screenshots',
				type: 'string',
				default: './Tests-Visual/screenshots'
			},
			compare: {
				alias: 'c',
				describe: 'Compare Base:Actual blinkdiff screenshots',
				type: 'string',
				default: 'base:actual'
			}
		})
		.parse();

	yargs.argv.uniqueIdentifier ? uniqueInstanceIdentifier = yargs.argv.uniqueIdentifier : uniqueInstanceIdentifier = nowDateTimeString;
	yargs.argv.artifactsPathOverrideParam ? artifactPath = yargs.argv.artifactsPathOverrideParam : artifactPath = path.join('.', 'Artifacts');

	if (isNaN(yargs.argv.concurrentClients)) {
		console.log('ERROR: Invalid --concurrentClients value.');
		process.exit(1);
	}

	// Process browsers
	if (!yargs.argv.browser || yargs.argv.browser.length == 0) {
		yargs.argv.browser.push('firefox');
	}
}
`

TestCare RC template:

`{
	"environment": "development",
	"environmentProject": "",
	"browsers": ["chrome"],
	"src": "./Tests",
	"reporter": [{
			"name": "spec"
		},
		{
			"name": "json",
			"output": "./Artifacts/report.json"
		},
		{
			"name": "xunit",
			"output": "./Artifacts/report.xml"
		},
		{
			"name": "html",
			"output": "./Artifacts/report.html"
		},
		{
			"name": "testrail",
			"output": "./Artifacts/report-testrails.log"
		}
	],
	"quarantineMode": false,
	"concurrency": 1,
	"skipJsErrors": true,
	"disableHttp2": true,
	"testExecutionTimeout": 900000,
	"filter": {
		"fixtureMeta": {},
		"testMeta": {}
	},
	"clientScripts": [{ "module": "axe-core/axe.min.js" }],
	"screenshots": {
		"path": "./Artifacts/",
		"pathPattern": "${OS_VERSION}/${BROWSER}_${BROWSER_VERSION}/${FIXTURE}/${TEST_INDEX}-${TEST}/${RUN_ID}/${FILE_INDEX}.png",
		"takeOnFails": true
	},
	"enabledFeatures": ""
}
`

**Comment by pateketrueke** [comment]
Please, format your code properly or upload it to a gist instead, it's bit hard to read and follow here, thank you!

**Comment by vlads11** [comment]
Thanks for the help here: https://gist.github.com/vlads11/4eae63c855a12edefc61bd9493be9520

**Comment by pateketrueke** [comment]
The custom flags (e.g. `--take-screenshot`) from this package CLI are not supported by Testcafé itself, in fact, they're hacked and extracted when the package is used on the test files: https://github.com/tacoss/testcafe-blink-diff/blob/master/lib/index.js#L10-L12

If you don't propagate those arguments through the `process.argv` object, you may try using the `process.env` variables instead, that way you can tell this module how to behave properly.

**Comment by vlads11** [comment]
Thanks for this, will give it a try and see how far I get.

**Comment by vlads11** [comment]
Thanks @pateketrueke - The issue was ultimately with process.env TAKE_SNAPSHOT variable that we were over writing in our Jenkins Job Defintiion. 100% appreciate the assist though, the lines of code you shared led me to the right solution and I learned much in the process.
