### ISSUE TITLE
Bug in Documentation

### ISSUE THREAD

**Issue by erolstt** [tacoss/testcafe-blink-diff#59]
Hi,
I noticed that in [here](https://github.com/tacoss/testcafe-blink-diff/blob/master/typings/index.d.ts#L43) it says 
_"0.03 # <= **3%** is OK"_
but in README
_"Note that v0.4.x will still treat 0.03 as 3% which may be confusing — since v0.5.x this value is kept as is, so 0.03 will be **0.03%** and nothing else!"_
As the current version is `0.5.3` should not the comment in index.d.ts be updated accordingly?

**Comment by pateketrueke** [comment]
Thank you, I have not noticed this before, gonna update the typings asap!
