### ISSUE TITLE
Compare stops if one image fails comparison

### ISSUE THREAD

**Issue by VRTOlli** [tacoss/testcafe-blink-diff#7]
Hello,

when I try to run the comparison on my base and actual images the process stops after one failed comparison, and no report is produced. 

npx testcafe-blink-diff e2e-tests/screenshots/testcafe --compare base:actual --open --threshold 0
Collecting screenshots...
Processing 10 files...
  test images/depthchart-colormap-1 DONE
  test images/depthchart-colormap-2 DONE
  test images/depthchart-target-depth DONE
[ERR] Failed with 0.32% of differences

The comparison stops after the third image fails and any image after that is not compared.

**Comment by pateketrueke** [comment]
Good catch, I'll be fixing this asap, thank you!

**Comment by pateketrueke** [comment]
Now the report is always built, regardless of any failure, however an exit-code is now used to indicate the overall result.

**Comment by VRTOlli** [comment]
Thanks, now all the comparisons are ran even though one fails. There is still one problem I am having, now even if all my images pass the comparison there is no report. I switched back to 0.3.15 from 0.4.0 and the report was generated.

**Comment by pateketrueke** [comment]
Oh my, I missed something else... sorry for that, I'll be sending a patch soon, thank you!
