### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by diogoweb2** [tacoss/testcafe-blink-diff#8]
Browser: HeadlessChrome 78.0.3904 / Windows 7.0.0

Hi, I can't run any test without this error. 
It always fail on the   takeSnapshot line. 

cmd:
npx testcafe chrome:headless tests/ -s tests/screenshots --take-snapshot
example (I tried other tests):
fixture("Snapshots").page("http://google.com");
test("check something here", async t => {
  await takeSnapshot(t);
});
![image](https://user-images.githubusercontent.com/6312058/68884641-924ab800-06e1-11ea-93b3-8ad5486b83e5.png)

**Comment by pateketrueke** [comment]
Gotcha, thanks for your feedback, I'll be fixing this asap!

**Comment by pateketrueke** [comment]
Hi, I hope the latest release solve this shame.

Actually, always it have to been working this wow, thank you!

**Comment by diogoweb2** [comment]
thanks! worked. :)

One quick question. (not sure if it's a bug or not so, I wont create as a
new item)

Is it possible to take a screenshot of the whole page (pages with scroll)
I've tried:
npx testcafe chrome tests/ -s tests/_screenshots/chrome
--take-snapshot --full-page actual
but no difference... THanks for your help and great work

**Comment by pateketrueke** [comment]
Please open a new issue, it will help other users as reference if they have the same. ;-)

**Comment by philga7** [comment]
@pateketrueke:

Good morning.

As of this comment, this particular issue is still producing issues:

`test('Highlight the intended hovered transaction', async (t: any) => {
    const cellItem = await transactionSummariesTable.getCellSelectorByRowAndColumn(0, 1);

    await t
        .hover(cellItem);

    await takeSnapshot(t, 'hoveredTransaction');
});`

...then...

`1) TypeError: Cannot read property 'reduce' of undefined`

Am I not invoking `takeSnapshot()` correctly, or is this bug still persisting?

Thanks!

-Phil

**Comment by pateketrueke** [comment]
Well, in the code we still have `selectors.reduce` so I think it's that line that produces the error... 

The test code you're using looks pretty well, actually I don't see any misusage there, make sure you're using the latest released version `0.4.3` of this package so please upgrade.

> I just released `0.4.3` to patch this behaviour, if the problem persists please ropen this ticket. Thank you!

**Comment by philga7** [comment]
@pateketrueke:

That did it (upping to 0.4.3) -- my apologies for not checking that before!

Thanks so much :)
