### ISSUE TITLE
fullscren screenshot

### ISSUE THREAD

**Issue by diogoweb2** [tacoss/testcafe-blink-diff#9]
Is it possible to take a screenshot of the whole page (pages with scroll)
I've tried:
npx testcafe chrome tests/ -s tests/_screenshots/chrome --take-snapshot --full-page actual

but it didn't work

thanks

**Comment by pateketrueke** [comment]
Have you tried to take the screenshot by hand?

I mean, behind the escenes `takeSnapshot` is calling `await t.takeScreenshot(...)` so you can try how it works, it that doesn't let you take the screenshot as you want then you need to review what's going on with your CSS and layout.

If you are able to take the screenshot properly, please let me know as it can be serve as fix for this kind of issues, thank you!

**Comment by diogoweb2** [comment]
sc

> Have you tried to take the screenshot by hand?
> 
> I mean, behind the escenes `takeSnapshot` is calling `await t.takeScreenshot(...)` so you can try to see how it works, if that doesn't let you take the screenshot as you want then you need to review what's going on with your CSS and layout.
> 
> If you are able to take the screenshot properly, please let me know as it can be serve as fix for this kind of issues, thank you!

Screenshot works fine but only takes the visible part of the page.
For longer pages , I'd like to know if it possible to include all the content. 
I could manually simulate a "page down keypress + take another screenshot" but for dynamic pages where I don't know the content size,  it wouldn't be a good solution.

**Comment by pateketrueke** [comment]
Interesting, so Testcafé is not able to take full-page screenshots?

According its docs they do if you enable that on the CLI, e.g. `-s fullPage=true`
